#!/usr/bin/env ruby
#
# Usage: ruby txt_error_decode.rb <error code>
# 
# Look up the result in the table


require 'awesome_print'
#require 'pry'

hex = ARGV[0]
bin = hex.upcase.hex.to_s(2)#.reverse

#bin.split('').each_with_index do |bit,i|
# puts "#{i}: #{bit}"
#end

s = {}

s["ac mod type"]             = bin[0..3]
s["ac mod progress codes"]   = bin[4..9]
s["ac mod error codes"]      = bin[10..14]
s["not generated by ac mod"] = bin[15]
s["tpm command return code"] = bin[16..24]
s["reserved"]                = bin[25..29]
s["software error"]          = bin[30]
s["valid error"]             = bin[31]

#s.values.each { |b| b = b.reverse! }
s['error code']      = hex.upcase
s['error in binary'] = bin

ap s

puts "progress code: %02dh" % s['ac mod progress codes'].to_i(2).to_s(16)
puts "   error code: %s" % s['ac mod error codes'] 

#binding.pry

